appName: adservice
appReplicas: 2
appImage: gcr.io/google-samples/microservices-demo/adservice
appVersion: v0.3.8
containerPort: 9555
containerEnvVars:
- name: PORT
  value: "9555"
- name: DISABLE_STATS
  value: "1"
- name: DISABLE_TRACING
  value: "1"
cpuRequest: 200m
memoryRequest: 180Mi
cpuLimits: 300m
memoryLimits: 300Mi

serviceType: ClusterIP
servicePort: 9555